version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
    #Webinterface 7474 nur für DebugZwecke, kann später entfernt werden!
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j-volume/data:/data
      - ./neo4j-volume/logs:/logs
