name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/setup-nasm@v1

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DSDL3IMAGE_VENDORED=OFF

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cp ${{github.workspace}}\build\Release\client.exe ${{github.workspace}}
        cp ${{github.workspace}}\build\Release\server.exe ${{github.workspace}}
        cp ${{github.workspace}}\build\SDL\Release\SDL3.dll ${{github.workspace}}
        cp ${{github.workspace}}\build\SDL_image\Release\SDL3_image.dll ${{github.workspace}}
        cp ${{github.workspace}}\build\SDL_net\Release\SDL3_net.dll ${{github.workspace}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: |
          client.exe
          server.exe
          SDL3.dll
          SDL3_image.dll
          SDL3_net.dll
          shaders
          palette.png
          spritesheet.png
